# Generated by Django 4.1 on 2022-09-15 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('conteudo', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=400)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
            ],
        ),
    ]
